### ISSUE TITLE
error CS0234, ApiClient.cs

### ISSUE THREAD

**Issue by tigon7476** [kazyx/kz-remote-api#13]
1> D: \ locana \ modules \ kz-remote-api \ Project \ Internal \ ApiClient.cs (1,23,1,27): error CS0234: Type or namespace 'Util' does not exist in namespace 'Kazyx.RemoteApi'. Make sure you have an assembly reference.

so I can not use ===> RemoteApiLogger.VerboseLog(request);

**Comment by kazyx** [comment]
Can you find `RemoteApiLogger.cs` at `Project/Util/RemoteApiLogger.cs`?

**Comment by tigon7476** [comment]
Thank you for your reply. 

Your code in Code page missed RemoteApiLogger.cs. Your source code in the code page is missing the RemoteApiLogger.cs file. I hope you include this and upload it again.

**Comment by kazyx** [comment]
I finally understand what you say.
`RemoteAPiLogger.cs` is missing in `KzRemoteApiDesktop.csproj`. I will fix it soon.

> Anyway, the output of this project is KzRemoteApiDesktop.dll, how can I use it?

Have you read `README.md`?
You can add this repository as a Project into your solution, or add `KzRemoteApiDesktop.dll` along with `Newtonsoft.Json.dll` into your solution.

> Do you have any test code?

No. It is welcome if you contribute test code.
