### ISSUE TITLE
Do not found device on Discovery

### ISSUE THREAD

**Issue by varadig** [kazyx/kz-remote-api#6]
Hi,

I try the desktop version of your code, but I cant discovery a connected device.
The device is connected over Wi-Fi, and I founded the device with this wrapper:
https://github.com/twenzel/SonyCameraRemoteControl
But twenzel wrapper support just the CameraRemoteAPI. 2.0, so I wanted to try your solution.

```
using System;
using Kazyx.DeviceDiscovery;

namespace KzRemoteAPIConsole
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			SsdpDiscovery discovery = new SsdpDiscovery();

			discovery.SonyCameraDeviceDiscovered += (_sender, e) => {
				var endpoints = e.SonyCameraDevice.Endpoints;
				Console.WriteLine("CAMERA END POINTS:"+endpoints.ToString());
			};
			discovery.Finished += (_sender, e) => {
				Console.WriteLine ("Finished");
			};

			discovery.DescriptionObtained += (_sender, e) => {
				Console.WriteLine("Description Obtained");	
			};

			discovery.SearchSonyCameraDevices ();
			Console.WriteLine ("DISCOVERY");

			while (true) {
				
			}
		}
	}
}

```

I got just this on the Console

```
Finished
DISCOVERY
```

**Comment by varadig** [comment]
I tried with QX30 and ILCE-5000 too

**Comment by kazyx** [comment]
Hi, thank you for the report.

Can you check with the latest revision?
https://github.com/kazyx/kz-ssdp-discovery/commit/a16cbf240d684f605225f1f5efbba219958b0ee4

**Comment by varadig** [comment]
Hi,

thanks, the latest version of the ssdp-discovery is working
